### ISSUE TITLE
How to use axisTextBuilder?

### ISSUE THREAD

**Issue by arijit-sen** [tajaouart/real_time_chart#1]
Couldn't find any implementation reference in the documentation.

I want to change the color of the text in x-axis when the data is getting streamed in the first example app.

**Comment by tajaouart** [comment]
Hello @arijit-sen 

You can use it like following :

```dart
RealTimeGraph(
  stream: stream,
  axisTextBuilder: (double value) {
    return Text(
      value.toString(),
      style: const TextStyle(color: Colors.green),
    );
  },
)
```
